# Perfil de Testing
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false

  flyway:
    enabled: false  # Deshabilitado para tests, usamos create-drop

  data:
    redis:
      host: localhost
      port: 6379
      database: 1  # Base de datos diferente para tests

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never

server:
  port: 0  # Puerto aleatorio para tests

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

jwt:
  secret: test-secret-key-for-testing-purposes-only
  expiration: 300  # 5 minutos para tests rápidos
  refresh-expiration: 600  # 10 minutos

cors:
  allowed-origins: "*"

logging:
  level:
    dev.kreaker.kinvex: WARN
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    org.springframework.test: INFO
    org.testcontainers: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Configuraciones específicas para testing
app:
  debug: false
  mock-external-services: true
  enable-test-endpoints: true
  test-mode: true
