# Perfil de Desarrollo
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kinvex}
    username: ${DB_USERNAME:kadmin}
    password: ${DB_PASSWORD:Hermione#00}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false
    clean-disabled: false
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: ${JWT_SECRET:bXl2ZXJ5bG9uZ3NlY3JldGtleXRoYXRpc2F0bGVhc3QyNTZiaXRzbG9uZzEyMzQ1Njc4OTBhYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5eg==}
  expiration: ${JWT_EXPIRATION:7200}  # 2 horas para desarrollo
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:172800}  # 2 días

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000

# Logging configurado en logback-spring.xml

# Configuraciones específicas para desarrollo
app:
  debug: true
  mock-external-services: true
  enable-test-endpoints: true
