# Perfil de Desarrollo
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kinvex_dev
    username: kinvex_dev
    password: dev_password
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

jwt:
  secret: dev-secret-key-for-development-only-not-secure
  expiration: 7200  # 2 horas para desarrollo
  refresh-expiration: 172800  # 2 días

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000

# Logging configurado en logback-spring.xml

# Configuraciones específicas para desarrollo
app:
  debug: true
  mock-external-services: true
  enable-test-endpoints: true
